### ISSUE TITLE
New version doesn't who pop up when completing a work on task

### ISSUE THREAD

**Issue by finn-matti** [ksalzke/work-on-omnifocus-plug-in#9]
Right now with the new version from a few days ago, if I complete a work on task it just gets deferred for an hour, but I don't get asked what I want to do with this task. Any ideas, what this could be?

EDIT: I just checked. The problem doesn't occur with Version 1.1.0 of the plug-in.

**Comment by ksalzke** [comment]
Hi @finn-matti 

Oops - this was my fault. Sorry!

I added some scheduling information in the dialogue which included creating a new function in the 'Scheduling' plug-in library. If you have that plug-in installed but not the latest version, the action fails silently. I suspect that is what was happening to you.

I've updated the latest version of the Scheduling plug-in, so you should be able to resolve by downloading its most recent version (recommended, because you'll get the additional information in the dialogue) but I've also updated this 'Work On' plug-in so that it continues even if the latest version isn't installed.

So should be fixed with 79944fe4463c1855cd0589e3fafa1bdbfc9a0c1b

Let me know if you still have issues after updating!

And thanks for letting me know the issue. :-)
